Обновил скрипты
ITOneNorthGateVologda/scripts pull request #1
Opened 2024-05-06 11:28 UTC by lvapl

https://github.com/ITOneNorthGateVologda/.github/issues/17

2024-05-06 12:01 UTC, olgapshen requested changes
Я бегло прошлась, в основном формат и конвенция. По самой структуре будет понятно, когда будет эмулятор Альфабанка.

2024-05-06 12:01 UTC, olgapshen commented on SMARTBUDGET/TABLES/User.sql
* Пустая строка
* Отдельная схема
* Может хранить не пароль, а хеш пароля?

2024-05-06 12:09 UTC, lvapl commented on SMARTBUDGET/TABLES/Account.sql
Тоже не знаю

2024-05-06 12:10 UTC, lvapl commented on SMARTBUDGET/TABLES/UserRoles.sql
По названиям - это Hibernate сделал, с Темой подумали пока что так оставить

2024-05-06 12:12 UTC, olgapshen commented on SMARTBUDGET/TABLES/Account.sql
Я нашла! Надо добавить .gitattribute файл. Это можно прямо в этом MR-е сделать и в будущем жить станет проще :)

https://stackoverflow.com/questions/28145687/why-does-git-think-my-sql-file-is-a-binary-file

2024-05-06 12:50 UTC, lvapl commented
Вечером буду занят макетом, поэтому завтра по PR пройдусь и справлю.
По поводу названий constraint'ов нужно обговорить с @sshiae, по остальным замечаниям согласен

2024-05-06 13:44 UTC, olgapshen commented on SMARTBUDGET/TABLES/Account.sql
https://github.com/ITOneNorthGateVologda/scripts/pull/2

2024-05-09 20:20 UTC, olgapshen commented
Очень долго MR висит. Предлагаю слить, потом перенесём в другую схему. Я нарежу задачи из Review.

2024-05-09 20:29 UTC, olgapshen approved these changes

2024-05-09 20:29 UTC, olgapshen commented
Ребята, задачи на будущее нарезала, сливайте!

2024-05-10 08:58 UTC, olgapshen commented
Так, оочень долго висит, я сливаю. @lvapl Витя... постарайся больше влиться в поток :) Мы без тебя не сможем.

2024-05-10 08:58 UTC, merged